spring.application.name=db

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${HOST:${DATABASE_HOST:localhost}}:${DATABASE_PORT:3306}/${NAME:${DATABASE_NAME:fifa}}?ssl-mode=REQUIRED&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DATABASE_USERNAME:${USER:root}}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DATABASE_PASSWORD:}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
